import React from "react";
const columns = [
  { name: "ID", uid: "id", sortable: true },
  { name: "EMPLOYEE_NAME", uid: "employee_name", sortable: true },
  { name: "ENROLLED_DATE", uid: "enrolled_date", sortable: true },
  { name: "EMAIL", uid: "email", sortable: true },
  { name: "ROLE", uid: "role", sortable: true },
  { name: "ADDRESS", uid: "address" },
  { name: "PHONE_NUMBER", uid: "phone_number", sortable: true },
  { name: "ACTIONS", uid: "actions" },
];

const employees = [
  {
    id: 1,
    employee_name: "James",
    enrolled_date: "2022.01.12",
    email: "james@gmail.com",
    role: "Stock Keeper",
    address: "Colombo",
    avatar: "/images/emp-1.jpg",
    phone_number: "0789343567",
  },
  {
    id: 2,
    employee_name: "Alex",
    enrolled_date: "2022.01.12",
    email: "james@gmail.com",
    role: "Customer Support",
    avatar: "/images/emp-2.jpg",
    address: "Kaluthara",
    phone_number: "0789343567",
  },
  {
    id: 3,
    employee_name: "Kevin",
    enrolled_date: "2022.01.12",
    email: "james@gmail.com",
    role: "Distribution Coordinator",
    avatar: "/images/emp-3.jpg",
    address: "Gampaha",
    phone_number: "0789343567",
  },
  {
    id: 4,
    employee_name: "Colin",
    enrolled_date: "2022.01.12",
    email: "james@gmail.com",
    role: "staff",
    avatar: "/images/emp-4.jpg",
    address: "Kurunegala",
    phone_number: "0789343567",
  },
  {
    id: 5,
    employee_name: "James",
    enrolled_date: "2022.01.12",
    email: "james@gmail.com",
    role: "staff",
    avatar: "/images/emp-4.jpg",
    address: "Kandy",
    phone_number: "0789343567",
  },
  {
    id: 6,
    employee_name: "James",
    enrolled_date: "234",
    email: "57",
    avatar: "/images/emp-4.jpg",
    role: "staff",
    address: "Negombo",
    phone_number: "0789343567",
  },
  {
    id: 7,
    employee_name: "James",
    enrolled_date: "543",
    email: "5",
    role: "staff",
    avatar: "/images/emp-4.jpg",
    address: "Negombo",
    phone_number: "0789343567",
  },
  {
    id: 8,
    employee_name: "James",
    enrolled_date: "12",
    email: "7",
    role: "staff",
    avatar: "/images/emp-4.jpg",
    address: "Negombo",
    phone_number: "0789343567",
  },
  {
    id: 9,
    employee_name: "James",
    enrolled_date: "43",
    email: "8",
    role: "staff",
    avatar: "/images/emp-4.jpg",
    address: "Negombo",
    phone_number: "0789343567",
  },
  {
    id: 10,
    employee_name: "James",
    enrolled_date: "2",
    email: "567",
    role: "staff",
    avatar: "/images/emp-4.jpg",
    address: "Negombo",
    phone_number: "0789343567",
  },
  {
    id: 11,
    employee_name: "James",
    enrolled_date: "89",
    email: "12",
    role: "staff",
    avatar: "/images/emp-4.jpg",
    address: "Negombo",
    phone_number: "0789343567",
  },
  {
    id: 12,
    employee_name: "James",
    enrolled_date: "23",
    email: "23",
    role: "staff",
    avatar: "/images/emp-4.jpg",
    address: "Negombo",
    phone_number: "0789343567",
  },
  {
    id: 13,
    employee_name: "James",
    enrolled_date: "12",
    email: "17",
    role: "staff",
    avatar: "/images/emp-4.jpg",
    address: "Negombo",
    phone_number: "0789343567",
  },
  {
    id: 14,
    employee_name: "James",
    enrolled_date: "23",
    email: "2",
    role: "staff",
    avatar: "/images/emp-4.jpg",
    address: "Negombo",
    phone_number: "0789343567",
  },
  {
    id: 15,
    employee_name: "James",
    enrolled_date: "89",
    email: "51",
    role: "staff",
    avatar: "/images/emp-4.jpg",
    address: "Negombo",
    phone_number: "0789343567",
  },
];

export { columns, employees };
